### ISSUE TITLE
Research Signup and Auth

### ISSUE THREAD

**Issue by arghasen** [CricketManager/CricketManager#1]
Research into all the signup and authentication providers and create a cost vs benefit chart. We will decide on the provider based on this research

**Comment by SaiKrishna1995may** [comment]
I am thinking to go with Keycloak as its open source and free of cost. Main part is except SaSS it supports OSS, SSO Suport, JWT Custom Claims and M2M.

**Comment by arghasen** [comment]
As per discussion we will go with clerk

**Comment by arghasen** [comment]
Clerk with its 10k free users seems the best option. @SaiKrishna1995may ok?

**Comment by SaiKrishna1995may** [comment]
Perfect way to start off.
