### ISSUE TITLE
Create favicon for Cricket Manager

### ISSUE THREAD

**Issue by arghasen** [CricketManager/CricketManager#26]
We need a good favicon for cricket manager

**Comment by SAMPRAJ009** [comment]
![IMG_20240606_174800](https://github.com/CricketManager/CricketManager/assets/171264855/a1bda850-17e3-4a04-a3f7-20fd3b810b12)
![IMG_20240606_174744](https://github.com/CricketManager/CricketManager/assets/171264855/dfb7344e-c42a-4b5f-9922-090c9d5db6e0)
![IMG_20240606_174725](https://github.com/CricketManager/CricketManager/assets/171264855/e349619c-62c9-49c8-a57f-b9d4b70e854d)
![IMG_20240606_174658](https://github.com/CricketManager/CricketManager/assets/171264855/b4701c7b-4cab-4094-a62c-7702dacba43c)
![IMG_20240606_174628](https://github.com/CricketManager/CricketManager/assets/171264855/4f15aa29-cdb4-43fe-a5af-48a3e504a9a9)
![IMG_20240606_174612](https://github.com/CricketManager/CricketManager/assets/171264855/85b639f4-5e34-470d-8b10-9e7e44581202)
![IMG_20240606_174555](https://github.com/CricketManager/CricketManager/assets/171264855/6d3ebf80-a051-4bd4-8e4d-d97d063f5369)
![IMG_20240606_174534](https://github.com/CricketManager/CricketManager/assets/171264855/df2e90f5-898e-477a-a068-b845724673ce)

**Comment by arghasen** [comment]
Solid hai bhai

**Comment by arghasen** [comment]
I love the tagline @SAMPRAJ009

**Comment by arghasen** [comment]
<img width="54" alt="Screenshot 2024-06-06 at 8 41 56 PM" src="https://github.com/CricketManager/CricketManager/assets/1138168/c1eecf19-64b5-4e44-97c0-3c62317223a6">
As for favicon we have this

**Comment by SAMPRAJ009** [comment]
👍 nice
