### ISSUE TITLE
UI Date Issue

### ISSUE THREAD

**Issue by skofficial116** [CricketManager/CricketManager#61]
- [ ]  **Date Issue**  (played at issue' reported by Sachin (year 1999))
![Screenshot 2024-08-10 202527](https://github.com/user-attachments/assets/33099d1f-3dc3-446a-ac25-9d1dba5251a1)

**Comment by arghasen** [comment]
is this still the case?

**Comment by skofficial116** [comment]
> is this still the case?

Yess.
While visiting at Send Friendly Option

**Comment by arghasen** [comment]
I see this, can u please confirm

**Comment by skofficial116** [comment]
yes it is still showing up as earlier
